---
name: Publish Package and Docker Image

concurrency:
  group: publish
  cancel-in-progress: true

# yamllint disable-line rule:truthy
on:
  release:
    types: [released]

jobs:
  build:
    uses: LinkedMink/.github/.github/workflows/build-npm-package.yml@main
    with:
      upload-build: true
  publish-npm:
    needs: build
    environment:
      name: publish
    uses: LinkedMink/.github/.github/workflows/publish-npm-package.yml@main
    with:
      upload-to-tag: ${{ github.ref_name }}
      uploaded-build-name: ${{ needs.build.outputs.uploaded-build-name }}
  publish-docker:
    needs: build
    environment:
      name: publish
    uses: LinkedMink/.github/.github/workflows/push-docker-hub-npm-package.yml@main
    with:
      upload-to-tag: ${{ github.ref_name }}
      uploaded-build-name: ${{ needs.build.outputs.uploaded-build-name }}
