---
name: Build NPM Package

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      node-js-version:
        type: string
        required: false
        default: "20"
        description: >-
          NodeJS version specifier (12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly,
          latest, node)
      upload-build:
        type: boolean
        required: false
        default: false
        description: "Upload distribution files to Github"
      publish-package:
        type: boolean
        required: false
        default: false
        description: "Publish to NPM registry after build"
      publish-registry-url:
        type: string
        required: false
        default: "https://npm.pkg.github.com"
        description: "NPM registry to use only for publishing"
    secrets:
      node-auth-token:
        required: false
        description: "Token to publish NPM packages, defaults to GITHUB_TOKEN"
    outputs:
      uploaded-build-name:
        description: "If a build is uploaded, this name will be output"
        value: ${{ jobs.build.outputs.uploadedBuildName }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      uploaded-build-name: ${{ steps.finish-output.outputs.uploaded-build-name }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          node-version: "${{ inputs.node-js-version }}"
      - name: Install Dependencies
        run: npm ci
      - name: Build Source
        run: npm run build
      - name: Lint Source
        run: npm run lint
      - name: Unit Test Source
        run: npm run test:ci
      - name: Package Artifacts
        if: inputs.upload-build
        run: |
          echo '::echo::on'
          echo "PACKAGE_FILE=$(npm pack | tail -1)" >> $GITHUB_ENV
      - name: Upload Artifacts
        if: inputs.upload-build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_FILE }}
          path: ${{ env.PACKAGE_FILE }}
      - id: finish-output
        name: Output Result
        if: inputs.upload-build
        run: |
          echo "uploaded-build-name=${PACKAGE_FILE}" >> $GITHUB_OUTPUT
      - name: Setup NodeJS Publish
        if: inputs.publish-package
        uses: actions/setup-node@v4
        with:
          registry-url: "${{ inputs.publish-registry-url }}"
      - name: Publish to NPM Registry
        if: inputs.publish-package
        run: |
          npm publish
        # run: npm dist-tag add example-package@1.4.0 stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token || secrets.GITHUB_TOKEN }}
