---
name: Publish NPM Package

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: "latest"
        description: "Tag for the NPM package: package-name@latest, package-name@beta"
      uploadedBuildName:
        type: string
        required: true
        description: "Name associated with actions/upload-artifact"
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        run: |
          echo '::echo::on'
          echo "${{ inputs.uploadedBuildName }}"
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.uploadedBuildName }}
          path: archive
      - name: Publish to NPM Registry
        run: |
          npm publish --tag "${{ inputs.tag }}" "archive/${{ inputs.uploadedBuildName }}"
        # run: npm dist-tag add example-package@1.4.0 stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
