---
name: Publish Artifacts for Tag

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      upload-to-tag:
        type: string
        required: true
        description: "Associate built Bundle with Github tag"
      uploaded-build-name:
        type: string
        required: true
        description: "Name associated with actions/upload-artifact"

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-gh-tag-${{ inputs.upload-to-tag }}
      cancel-in-progress: true
    steps:
      - name: Debug Output
        run: |
          echo '::echo::on'
          echo "${{ inputs.uploaded-build-name }}"
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.uploaded-build-name }}
          path: archive
      - name: Associate with Github Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: archive/*
          tag: ${{ inputs.upload-to-tag }}
          overwrite: true
          file_glob: true
          prerelease: true
