---
name: Publish NPM Package

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      imageScope:
        type: string
        required: true
        description: |
          For an image: [Registry]/?[Namespace]/[Image]:[Tag], The [Registry]/[Namespace]
      uploadedBuildName:
        type: string
        required: true
        description: "Name associated with actions/upload-artifact"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        run: |
          echo '::echo::on'
          echo "${{ inputs.uploadedBuildName }}"
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.uploadedBuildName }}
          path: archive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract and Read Version
        run: |
          tar --extract --verbose --file="archive/${{ inputs.uploadedBuildName }}"
          echo "VERSION=$(cd package && npm pkg get version | sed 's/"//g')" >> $GITHUB_ENV
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          build-args: "ENVIRONMENT=production"
          file: "package/docker/Dockerfile"
          platform: |
            linux/amd64
            linux/amd64/v3
            linux/arm64
            linux/arm/v7
          context: ./package
          push: true
          tags: |
            ${{ inputs.imageScope }}:latest
            ${{ inputs.imageScope }}:$VERSION
