---
name: Validate Main

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Validate GitHub Actions YML
        run: |
          yamllint -c yamllint-config.yaml \
            .github/workflows/*.yml \
            workflow-templates/nodejs/*.yml
